### ISSUE TITLE
Update readme using yarn instead of npm

### ISSUE THREAD

**Issue by DzmitryShylovich** [qdouble/angular-webpack2-starter#122]
https://yarnpkg.com/en/docs/cli/run

**Comment by qdouble** [comment]
Just installed it and tried it out for a bit....it seems way faster, but the script command don't seem to work the same....so I'd have to change all the script to be based on yarn?

**Comment by qdouble** [comment]
seems I need to wait for them to publish this fix to npm as well as it doesn't run the postinstall script right now: https://github.com/yarnpkg/yarn/commit/cb00d27abc1f442e7f5eb6223b8b5c31dacb115d

**Comment by bmayen** [comment]
I'd prefer to wait a bit to move over to Yarn. While it works great for simpler use cases, there are a lot of edge cases that work with NPM but not yet with Yarn.

**Comment by qdouble** [comment]
like what in particular?

**Comment by DzmitryShylovich** [comment]
It's just readme. If u want/need to use npm then use it :)

**Comment by qdouble** [comment]
from what I'm seeing, yarn doesn't seem like a drop in replacement though....at least not yet, may have to change the scripts to work for it.

**Comment by bmayen** [comment]
> like what in particular?

Too much to list here, but if you looks at their github issues, you'll see there's still a lot of work to do. But a couple things that affected us right off the bat: https://github.com/yarnpkg/yarn/issues/513, https://github.com/yarnpkg/yarn/issues/678

> It's just readme. If u want/need to use npm then use it :)

My point was more in response to making changes to scripts here in order to support Yarn. If it's *just* a README update, then no problem.

**Comment by qdouble** [comment]
@bmayen I'll keep an eye on those issues. I definitely want to switch over eventually.
