### ISSUE TITLE
Debugging TypeScript files instead of js

### ISSUE THREAD

**Issue by Waterstraal** [qdouble/angular-webpack2-starter#126]
Debugging doesn't seem to be working on the original TypeScript files, but on the transpiled js files? Chrome dev tools say it's showing a .ts file, but the contents are definitely not the original. 

See attachment:
![screenshot 2016-10-13 11 25 52](https://cloud.githubusercontent.com/assets/2691730/19343889/6ad7f8a4-9138-11e6-8dcf-930409a9ff79.png)

**Comment by qdouble** [comment]
@Waterstraal In the constants.js file (https://github.com/qdouble/angular-webpack2-starter/blob/master/constants.js#L26) instead of 'eval', set it to one of the others here: https://webpack.github.io/docs/configuration.html#devtool . It's just set to use 'eval' by default as it's the fastest, but if you used the full 'source-map', then it should show the original ts file.

**Comment by helzgate** [comment]
Changing it to '#inline-source-map' worked for me
