### ISSUE TITLE
styleURL

### ISSUE THREAD

**Issue by rushstrike** [qdouble/angular-webpack2-starter#136]
I tried defining a style URL  in my component and when i run npm start:

ERROR in ./src/app/features/map/map.scss
Module parse failed: /src/app/features/map/map.scss Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
| .sebm-google-map-container {
|      height: 500px;
| }

How does it not have a scss loader?

**Comment by qdouble** [comment]
@rushstrike just use `npm run sass` if you create a new sass file. Most of the scripts run node-sass first, but not that one as it creates a loop. We're not currently using a sass loader because the ngc/AOT compiler cannot process SASS, this will change when we switch over to using the webpack AOT plugin(https://github.com/qdouble/angular-webpack2-starter/issues/112)...but it still has bugs, so we can't switch yet.
