### ISSUE TITLE
PostCSS in style build process

### ISSUE THREAD

**Issue by dschewchenko** [qdouble/angular-webpack2-starter#144]
Hi
I'm using sass loader, But solution from postcss guide doesnt work, all output styles without postcss autoprefixing
How I can to add postcss in build process?

My conf sor scss filetype:
`{
        test: /\.scss$/,
        use: [
          'raw-loader',
          'sass-loader',
          {
            loader: 'postcss-loader',
            options: {
              plugins: function () {
                return [
                  require('autoprefixer')({browsers: ['>0.1%']})
                ]
              }
            }
          }
        ]
      },`

**Comment by Matmo10** [comment]
I also tried in vain to get this working (https://github.com/TheLarkInn/angular2-template-loader/issues/35 , https://github.com/postcss/postcss-loader/issues/113) .

I gave up on webpack integration and just did this:

- Add postcss, postcss-cli, autoprefixer to your dependencies.
- Add a new npm script: 
```
    "autoprefixer": "postcss -u autoprefixer --autoprefixer.browsers 'last 2 versions' -r src/app/**/*.css"
```

- Then I changed all my other npm scripts to look like this:
```
    "postinstall": "npm run sass && npm run autoprefixer",
    "e2e": "npm run sass && npm run autoprefixer && npm-run-all -p -r e2e:server e2e:only",
    "pretest": "npm run lint && npm run sass && npm run autoprefixer",
    "pretest:once": "npm run lint && npm run sass && npm run autoprefixer",
    "compile:aot": "npm run sass && npm run autoprefixer && npm run clean:compile && npm run ngc && npm run build:aot",
    "compile:dev": "npm run sass && npm run autoprefixer && npm run clean:compile && npm run ngc && npm run build:aot:dev",
    "compile:only": "npm run clean:compile && npm run sass && npm run autoprefixer && npm run ngc",
    "prebuild": "rm -rf dist && npm run sass && npm run autoprefixer",

```

This works for producing a prod build or testing or whatever, but you would have to manually run `npm run autoprefixer` to continuously generate the autoprefixed css, which is tolerable I guess since people are generally using newer browsers anyways while developing.

Still, I'd be curious to see what a proper webpack integration would look like. But I know @qdouble had plans to use the webpack aot plugin sometime soon, which would allow .scss file references in components, which will have some impact on the webpack config of this project (switching to a sass loader instead of raw-loader, I'd guess?), so maybe that will make the integration with postcss--loader easier.

**Comment by qdouble** [comment]
@Matmo10 is correct... until we can switch over to using the AOT plugin, the only safe way to process postcss would be to run it as a different node process. I'll revisit this whenever we switch over.

**Comment by dschewchenko** [comment]
Thanx for your answers)
For prod building it's enough
