### ISSUE TITLE
File/Folder structure

### ISSUE THREAD

**Issue by John0x** [qdouble/angular-webpack2-starter#149]
Hey, I just wanted to ask whether the file structure was intended to be like it is currentyl?

It all seems a bit confusing. I mean a folder named reducers which doesn't contain the reducers, a folder named services, which doesn't contain services.
I'm not sure about the standards regarding ng2/redux folder structure, but doesn't that seem a bit unclear?

A short introduction the the structure would be great!

**Comment by qdouble** [comment]
Well the reducers folder does contain the main reducer. 

As far as the exact folder structure, I didn't delve to deep into it as it depends on whether or not you want to lazy load most of your stuff.
 
If you're not going to be doing a lot of lazy loading, then you can put your reducers/services/actions/effects etc in their own folders

However, if you are going to be doing a lot of lazy loading, then it would make more sense to put your reducers/services/actions/effects in the feature folders so that they will only be loaded when you load that particular feature module.
