### ISSUE TITLE
Not able to run unit test case/e2e test cases

### ISSUE THREAD

**Issue by yvChauhan** [qdouble/angular-webpack2-starter#235]
Hi,

I just downloaded your starter and tried its default sample, however, it looks like Test is not working at all, Let me know if you want more specific logs.

**Comment by qdouble** [comment]
@yvChauhan hey, yes, giving me the branch, which specific test and the log would be helpful

**Comment by MaxSan** [comment]
Unsure if its the same issue but im getting this error on master/standard starter pack after running the combi test

> npm ERR! node v7.4.0
> npm ERR! npm  v4.0.5
> npm ERR! code ELIFECYCLE
> npm ERR! angular-webpack2-starter@1.15.0 e2e:jit: `npm run build:prod:e2e && npm run e2e`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the angular-webpack2-starter@1.15.0 e2e:jit script 'npm run build:prod:e2e && npm run e2e'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the angular-webpack2-starter package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     npm run build:prod:e2e && npm run e2e
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs angular-webpack2-starter
>

**Comment by ricricucit** [comment]
To me it lints most files (maybe all) warning about white spaces, etc. and than breaks with this:

````
npm ERR! Darwin 16.4.0
npm ERR! argv "/Users/my_user/.nvm/versions/node/v7.5.0/bin/node" "/Users/my_user/.nvm/versions/node/v7.5.0/bin/npm" "run" "tslint" "src/app/**/*.ts"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! angular-webpack2-starter@1.15.0 tslint: `tslint "src/app/**/*.ts"`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the angular-webpack2-starter@1.15.0 tslint script 'tslint "src/app/**/*.ts"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-webpack2-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tslint "src/app/**/*.ts"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-webpack2-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-webpack2-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Applications/MAMP/htdocs/giveaways/npm-debug.log

npm ERR! Darwin 16.4.0
npm ERR! argv "/Users/my_user/.nvm/versions/node/v7.5.0/bin/node" "/Users/my_user/.nvm/versions/node/v7.5.0/bin/npm" "run" "lint"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! angular-webpack2-starter@1.15.0 lint: `npm run tslint "src/app/**/*.ts" `
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-webpack2-starter@1.15.0 lint script 'npm run tslint "src/app/**/*.ts" '.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-webpack2-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run tslint "src/app/**/*.ts"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-webpack2-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-webpack2-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Applications/MAMP/htdocs/giveaways/npm-debug.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
````

**Branch**: _no-universal-support_

**Debug file:** [npm-debug.txt](https://github.com/qdouble/angular-webpack2-starter/files/783856/npm-debug.txt)

This after upgrading to:
`"typescript": "^2.1.6",` and `"tslint": "^4.4.2",`
...because before it was failing with `Cannot find module './test/parse'` which was worse.

**Comment by ricricucit** [comment]
OK, I figured it out...mostly thanks to [this discussion](https://github.com/palantir/tslint/issues/1770) and by noticing that `yarn karma start` alone was working just fine.

Steps followed:
1. updated tslint to see if _tslint/test_ folder was gonna show up [optional step, if you want to keep the version you currently have]
2. removed (temporarily) the term "test" from the `.yarnclean` file
3. reinstalled all packages using `yarn`
4. Fixed ALL warnings and errors thrown by `yarn karma start` (because I've noticed that some of them were making the "`yarn test` process crashing")
5. rerun `yarn test`, which at this point was working again.

🤞 Good luck.
